name: gulgrir
services:
  app:
    build:
      context: ..
      dockerfile: docker/app.Dockerfile
    image: gulgrir:dev
    container_name: gulgrir_web
    restart: unless-stopped
    env_file: ../.env
    ports:
      - "${GULGRIR_PORT-8765}:8765"
    depends_on:
      - db
    entrypoint: ["/app/docker/scripts/entrypoint.sh"]
    command: "gunicorn gulgrir.wsgi:application --bind 0.0.0.0:8765 --workers 2"

  db:
    image: postgres:16
    env_file: ../.env
    restart: unless-stopped
    container_name: gulgrir_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
