# Generated by Django 5.2.1 on 2025-05-11 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('media_type', models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('game', 'Game'), ('music', 'Music'), ('show', 'Show'), ('other', 'Other')], default='other', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_project', models.BooleanField(default=False)),
                ('title_override', models.CharField(blank=True, max_length=255, null=True)),
                ('shelf', models.CharField(choices=[('backlog', 'Backlog'), ('in_progress', 'In Progress'), ('done', 'Done')], default='backlog', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_user_items', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tracker.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserItemHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happened_at', models.DateTimeField(auto_now_add=True)),
                ('event_type', models.CharField(choices=[('completed', 'Completed'), ('revisited', 'Revisited')], max_length=20)),
                ('user_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tracker.useritem')),
            ],
        ),
    ]
