# Generated by Django 5.2.1 on 2025-05-19 06:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_tag_useritem_tags_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritemhistory',
            name='happened_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
