# Generated by Django 5.2.1 on 2026-01-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_savedfilter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='media_type',
            field=models.CharField(choices=[('book', 'Book'), ('movie', 'Movie'), ('game', 'Game'), ('music', 'Music'), ('show', 'Show'), ('anime', 'Anime'), ('other', 'Other'), ('light_novel', 'Light Novel'), ('manga', 'Manga')], default='other', max_length=20),
        ),
    ]
