# Generated by Django 5.2.1 on 2026-01-21 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_alter_item_media_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='tier',
            field=models.PositiveSmallIntegerField(choices=[(0, '-'), (1, 'S'), (2, 'A'), (3, 'B'), (4, 'C'), (5, 'D'), (6, 'E'), (7, 'F')], db_index=True, default=0),
        ),
    ]
