# Generated by Django 5.2.1 on 2026-03-02 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0010_profile_theme'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queue',
        ),
    ]
