# Generated by Django 5.2.1 on 2026-03-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_delete_queue'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useritemhistory',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useritemhistory',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useritemhistory',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
