# Generated by Django 5.2.1 on 2026-03-09 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0012_useritem_timer_started_at_useritemhistory_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_layouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('order', 'name'),
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TimeBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='tracker.timebucket')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='tracker.timelayout')),
            ],
            options={
                'ordering': ('order', 'name'),
                'unique_together': {('layout', 'parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='TimeBucketAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ignored', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bucket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='tracker.timebucket')),
                ('user_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_assignments', to='tracker.useritem')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='tracker.timelayout')),
            ],
            options={
                'unique_together': {('layout', 'user_item')},
            },
        ),
    ]
