# Generated by Django 5.2.13 on 2026-04-26 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0021_timebucketassignment_assignment_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='time_default_layout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_profiles', to='tracker.timelayout'),
        ),
    ]
